---
title: "Modeling with Caret"
output:
  html_document:
    df_print: paged
---

**This document serves as a record of different attempts to model match outcomes using the 'caret' package.**

```{r setup, echo=F, message=F, warning=F}
library(dplyr)
library(zoo)
library(caret)
library(RANN)
library(tidyr)
library(ggplot2)
library(broom)
library(nnet)
source(file = "engineering_seriea_design_matrix.R") # runs in under 2 seconds
set.seed(5590)
```


```{r Preprocess, echo=F}
# Imputing missing values with bagImpute (form for newly promoted teams)
DF <- DF %>% select(-game_id,-season)
ppi <- preProcess(DF,method = "bagImpute")
DF_Imputed <- predict(ppi,DF)

```



```{r Nesting Data}
# Nesting data by team - creates a list of dataframes, one for each team's results.
teams <- unique(DF_Imputed$`Home Team`)
nested_DF <- list()

for (i in teams){
  temp_df <- DF_Imputed %>% filter(`Home Team`==i|`Away Team`==i)
  
  # adding in arbitrary time factor -- IS THIS NECESSARY?
  #  test_dates <- seq.Date(from=as.Date("1900-01-01"),to=as.Date("2019-01-01"), by="year")
  #  test_dates <- test_dates[1:nrow(temp_df)]
  #  temp_df <- cbind(temp_df,test_dates)
  
  nested_DF[[i]] <- temp_df
}


nested_DF_orig <- nested_DF

# Filtering to 2018-19 teams only
# Pescara, HellasVerona, Crotone, Benevento, Palermo
nested_DF <- nested_DF[c("Roma","Juventus","Milan","Atalanta","Bologna","Chievoverona","Empoli",
                         "Genoa","Lazio","Napoli","Inter","Cagliari","Fiorentina","Sampdoria",
                         "Sassuolo","Torino","Udinese","Spal","Parma","Frosinone")]

# for(i in 1:length(nested_DF)){ print(dim(nested_DF[[i]]))}

# Filtering out Parma, Frosinone which have no data from previous Serie A season

nested_DF <- nested_DF[c("Roma","Juventus","Milan","Atalanta","Bologna","Chievoverona","Empoli",
                         "Genoa","Lazio","Napoli","Inter","Cagliari","Fiorentina","Sampdoria",
                         "Sassuolo","Torino","Udinese","Spal")]

for(i in 1:length(nested_DF)){ print(dim(nested_DF[[i]]))}


```



```{r Loop Pred }


# Train/Test Sets
team_part <- list()

for(i in names(nested_DF)){
  
  temp <- nested_DF[[i]]
  obs<-nrow(temp)
  
  # Test set is the final season (last 24 observations)
  temp_test <- temp[(obs-23):obs, ]
  
  # Train set is all observations that come before
  temp_train <- temp[1:(obs-23), ] 

  Out<-list(i,temp_train,temp_test)  
  
  team_part[[i]] <- Out
}


# Create Timeslices TimeControl
my_TimeControl <- trainControl(method="timeslice",
                               initialWindow = 10,
                               horizon=1,
                               fixedWindow = FALSE)


team_model <- list()

x <- proc.time() 
for(i in 1:length(team_part)){

  temp <- team_part[[i]]
  
  name <- temp[[1]]
  train <- temp[[2]]
  test <- temp[[3]]
  
  # Training RF
  rfFit1 <- train(result~., data=train,
                  method="rf",trControl=my_TimeControl)
  
  # Output of time  
  #rfFit1$times$everything
  
  # Prediction
  rfRes1 <- predict(rfFit1,test)
  actual<- test %>% select(result)
  
  # Results in a confusion matrix
  Results<-confusionMatrix(rfRes1, as.factor(actual$result))
  
  team_model[[i]] <- list(name,rfFit1,rfRes1,Results)

}

y <- proc.time() 
y-x # about 7 minutes to run

# Troubleshooting? 
# https://stackoverflow.com/questions/13495041/random-forests-in-r-empty-classes-in-y-and-argument-legth-0
# https://stackoverflow.com/questions/26828901/warning-message-missing-values-in-resampled-performance-measures-in-caret-tra

# Extracting Team name, accuracy

rf_results <- list()
for(i in 1:length(team_model)){

  name<- team_model[[i]][[1]]
  acc <- team_model[[i]][[4]]$overall[[1]]  

  r <- as.data.frame(acc)

  rf_results[[i]] <- r
  }

rf_final <- bind_rows(rf_results)
rownames(rf_final) <- names(team_part)

rf_final %>% arrange(desc(acc))


```

# Neural Net

```{r}

team_model_nn <- list()

x <- proc.time() 
for(i in 1:length(team_part)){

  temp <- team_part[[i]]
  
  name <- temp[[1]]
  train <- temp[[2]]
  test <- temp[[3]]
  
  # Training RF
  NNFit1 <- train(result~., data=train,
                  method="nnet",trControl=my_TimeControl,
                  linout = TRUE)
  
  # Output of time  
  #rfFit1$times$everything
  
  # Prediction
  NNRes1 <- predict(NNFit1,test)
  actual<- test %>% select(result)
  
  # Results in a confusion matrix
  Results<-confusionMatrix(NNRes1, as.factor(actual$result))
  
  team_model_nn[[i]] <- list(name,rfFit1,rfRes1,Results)

}

y <- proc.time() 
y-x # about 38 minutes

# Troubleshooting? 
# https://stackoverflow.com/questions/13495041/random-forests-in-r-empty-classes-in-y-and-argument-legth-0
# https://stackoverflow.com/questions/26828901/warning-message-missing-values-in-resampled-performance-measures-in-caret-tra

# Extracting Team name, accuracy

nn_results <- list()
for(i in 1:length(team_model_nn)){

  name<- team_model_nn[[i]][[1]]
  acc <- team_model_nn[[i]][[4]]$overall[[1]]  

  r <- as.data.frame(acc)

  nn_results[[i]] <- r
  }

nn_final <- bind_rows(nn_results)
rownames(nn_final) <- names(team_part)

nn_final %>% arrange(desc(acc))
```


